package constants.enums;

public enum PageNames {
    HOME_PAGE,
    SIGN_IN_PAGE,
    REGISTER_PAGE,
    NOT_FOUND_404,
    TEST_JSP,
    ABOUT_PAGE,
    SHOP,
    CONTACT_US,
    PRODUCT,
    EMPTY_SHOP, CART, EMPTY_CART, CHECKOUT, MINI_CART, CARD_EDIT, CARD_DEFAULT, CARD_BOOK, CARD_ADD, TEST_USER_JSP, ADD_PRODUCT,
    USER_DASH_PAGE,


}
